version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
  save_cache:
    steps:  
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  build:
    steps:
      - checkout
      - restore_cache_cmd
      - run: mvn clean package
executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:8-jdk
jobs:
  build_artifact:
    executor: docker-executor
    steps:
      - build
workflows:
  build_artifact:
    jobs:
      - build_artifact
