version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/maven:3.6 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: mvn clean install # run the `echo` command
workflows:
  version: 2
  build:
    jobs:
      - build	
