version: 2.1

jobs:
  maven_build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          command: |
            mvn clean install;	  
            mkdir ~/artifacts;
            echo "./target/gs-spring-boot-0.1.0.jar" > ~/artifacts/springboot.jar;
      - store_artifacts:
          path: ~/artifacts/springboot.jar
workflows:
  version: 2
  maven_build_push:
    jobs:
      - maven_build
