version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:16.0.1-jdk-buster
    working_directory: /tmp
    steps:   
      # package into a jar
      - run: mvn clean package
      - run:
        command: |
          mkdir /tmp/artifacts;
          echo "./target/*.jar" > /tmp/artifacts/springboot.jar;
      - store_artifacts:
          path: /tmp/artifacts/springboot.jar
