version: 2.1

commands:
  store_artifacts_cmd:
    steps:
      - store_artifacts: # store the uberjar as an artifact
          path: target/gs-spring-boot-0.1.0.jar  
  build:
    steps:
      - checkout
      - run: 
          command: |
            mvn clean install;
            ls -l;
      - store_artifacts_cmd
      - persist_to_workspace:
          root: target
          paths:
            - gs-spring-boot-0.1.0.jar
  build_push_to_ecr_cmd:
    steps:
      - checkout	
      - run:
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 179746471541.dkr.ecr.us-east-1.amazonaws.com
            docker build -t springboothello .
            docker tag springboothello:latest 179746471541.dkr.ecr.us-east-1.amazonaws.com/springboothello:latest
            docker push 179746471541.dkr.ecr.us-east-1.amazonaws.com/springboothello:latest    
executors:
  java-executor:
    docker:
      - image: circleci/openjdk:8-jdk
  docker-executor:
    docker:
      - image: docker:18.06.1-ce-git      
jobs:
  build_artifact:
    executor: java-executor
    steps:
      - build
  build_and_publish_docker_image:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: target
      - setup_remote_docker
      - build_push_to_ecr_cmd
workflows:
  build_artifact:
    jobs:
      - build_artifact
      - build_and_publish_docker_image:
          requires:
            - build_artifact
